# Generated by Django 4.0.1 on 2022-01-24 20:30

from django.db import migrations, models
import wordle.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='solution',
            field=models.CharField(default=wordle.models.Game.random_solution, max_length=5),
        ),
    ]
