# Generated by Django 4.0.1 on 2022-01-24 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_alter_game_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
